apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhooq-dmc-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jhooq-dmc-front
  template:
    metadata:
      labels:
        app: jhooq-dmc-front
    spec:
      containers:
        - name: dmc-front
          image: princeay0n/jhooq-docker-demo:jhooq-docker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: jhooq-dmc-front
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jhooq-dmc-front
